# GENERATED by fr1j0/claude-light release.yml — do not edit by hand.
# Source template: fr1j0/claude-light Casks/claude-light.rb

cask "claude-light" do
  version "0.14.0"
  sha256 "e392691e4bb4ec39c8000083e9a12943aa2f5ae0918751d78bc95049d4392e82"

  url "https://github.com/fr1j0/claude-light/releases/download/v#{version}/claude-light.zip"
  name "Claude Light"
  desc "Menu-bar status light for Claude Code sessions"
  homepage "https://github.com/fr1j0/claude-light"

  depends_on macos: :ventura

  app "Claude Light.app"

  caveats <<~EOS
    Launch Claude Light, then use "Install Claude Code hooks" from the menu
    to wire it into ~/.claude/settings.json.

    Current releases are unsigned interim builds (Apple notarization pending),
    so Gatekeeper may report the app as "damaged and can't be opened".
    Clear the quarantine flag and launch again:
      xattr -dr com.apple.quarantine "#{appdir}/Claude Light.app"
  EOS
end
