# GENERATED by fr1j0/hive-light release.yml — do not edit by hand.
# Source template: fr1j0/hive-light Casks/hive-light.rb

cask "hive-light" do
  version "0.27.0"
  sha256 "d45a3ed05c785b83e41aae542f165abd46470de6e791bfb92a3f99aef784399a"

  url "https://github.com/fr1j0/hive-light/releases/download/v#{version}/hive-light.zip"
  name "Hive Light"
  desc "Menu-bar status light for Claude Code sessions"
  homepage "https://github.com/fr1j0/hive-light"

  depends_on macos: :ventura

  app "Hive Light.app"

  caveats <<~EOS
    Launch Hive Light, then use "Install Claude Code hooks" from the menu
    to wire it into ~/.claude/settings.json.

    Current releases are unsigned interim builds (Apple notarization pending),
    so Gatekeeper may report the app as "damaged and can't be opened".
    Clear the quarantine flag and launch again:
      xattr -dr com.apple.quarantine "#{appdir}/Hive Light.app"
  EOS
end
