# GENERATED by fr1j0/hive-light release.yml — do not edit by hand.
# Source template: fr1j0/hive-light Casks/hive-light.rb

cask "hive-light" do
  version "0.26.0"
  sha256 "d95fb5e5b994d1d6b4d227b5b0d6c013a0d6b9ca97b1d389a4fe1fb0ddee32a0"

  url "https://github.com/fr1j0/hive-light/releases/download/v#{version}/hive-light.zip"
  name "Hive Light"
  desc "Menu-bar status light for Claude Code sessions"
  homepage "https://github.com/fr1j0/hive-light"

  depends_on macos: :ventura

  app "Hive Light.app"

  caveats <<~EOS
    Launch Hive Light, then use "Install Claude Code hooks" from the menu
    to wire it into ~/.claude/settings.json.

    Current releases are unsigned interim builds (Apple notarization pending),
    so Gatekeeper may report the app as "damaged and can't be opened".
    Clear the quarantine flag and launch again:
      xattr -dr com.apple.quarantine "#{appdir}/Hive Light.app"
  EOS
end
